name: _deploy

on: # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  workflow_call:
    inputs:
      runs-on:
        description: The default build-agent
        type: string
        required: false
        # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        default: "ubuntu-20.04"
      stage:
        description: The stage to deploy to
        type: string
        required: false
        default: test

jobs:
  version:
    runs-on: ${{ inputs.runs-on }}
    outputs: # NOTE: We need the output in other jobs
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: "5.x"
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # For gitversion
    # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/index.md
    - id: gitversion
      name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true

  fuu:
    runs-on: ${{ inputs.runs-on }}
    if: inputs.stage == 'f'
    steps:
    - name: Deploy
      run: |
        echo "Deploying ${{ needs.version.outputs.semVer }} to '${{ inputs.stage }}'"

  deploy:
    runs-on: ${{ inputs.runs-on }}
    needs: ["version", "fuu"]
    # Always run this job except there was a failure in the previous jobs
    # https://github.community/t/run-a-job-if-at-least-one-of-the-previous-ones-succeeded/163777 
    if: ${{ always() && contains(needs.*.result, 'success') && !(contains(needs.*.result, 'failure')) }}
    steps:
    - name: Deploy
      run: |
        echo "Deploying ${{ needs.version.outputs.semVer }} to '${{ inputs.stage }}'"