name: _stage

on: # https://docs.github.com/en/actions/learn-github-actions/reusing-workflows
  workflow_call:
    inputs:
      runs-on:
        description: The default build-agent
        type: string
        required: false
        # See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        default: "ubuntu-20.04"
      from:
        description: The source branch
        type: string
        required: false
        default: main
      to:
        # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        description: The branch to merge into
        type: string
        required: false
        default: test

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#defaults
defaults:
  run:
    shell: bash

# https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#jobs
jobs:
  version:
    runs-on: ${{ inputs.runs-on }}
    outputs: # NOTE: We need the output in other jobs
      semver: ${{ steps.gitversion.outputs.semVer }}
    steps:
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # For gitversion
      # https://github.com/GitTools/actions/blob/main/docs/examples/github/gitversion/index.md
      - id: gitversion
        name: Determine Version
        uses: gittools/actions/gitversion/execute@v0.9.7
        with:
          useConfigFile: true

  # TODO: Add quality gates (e.g. SonarCloud)

  pr:
    runs-on: ${{ inputs.runs-on }}
    needs: version
    steps:
    # https://github.com/repo-sync/pull-request
    - uses: actions/checkout@v2
    - id: pr
      uses: repo-sync/pull-request@v2
      with:
        destination_branch: ${{ inputs.to }}
        source_branch: ${{ inputs.from }}
        pr_title: Deploy ${{ needs.version.outputs.semver }} to ${{ inputs.to }} stage 
        pr_body: |
          Approve and merge in order to stage changes to ${{ inputs.to }} stage.
          New version: ${{ needs.version.outputs.semver }} 
        pr_draft: false
        pr_reviewer: consileo-stoe/
        github_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Print
      run: |
        echo "Pull Request Number - ${{ steps.cp.outputs.pr_number }}"
        echo "Pull Request URL - ${{ steps.cp.outputs.pr_url }}"
