name: web-client
on:
  push:
    branches:
      - main
    paths:
      - "web-client/**"
  #--- TODO: For now also enable manual runs
  workflow_dispatch:

jobs:
  build:
    uses: consileo-stoe/test-gh-pr/.github/workflows/_stage.yml@main